library(DBI)
library(readr)
df <- read.csv('data.csv', sep = ',')
df$Categorie = as.factor(df$Categorie)
df$Gender = as.factor(df$Gender)
df$Marque = as.factor(df$Marque)
df$Forme = as.factor(df$Forme)
df$Structure = as.factor(df$Structure)
df$`Material Fond` = as.factor(df$`Material Fond`)
df$`Material Front` = as.factor(df$`Material Front`)
df$Taille = as.factor(df$Taille)
df$`Taille Temple` = as.factor(df$`Taille Temple`)
df$year <- as.numeric(df$year)
